const mockUser = {
    id: 1,
    username: 'testuser',
    email: 'user@test.com',
    isadmin: false
}

const mockToken = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOjEsImlz
    QWRtaW4iOmZhbHNlLCJpYXQiOjE3MDg0NTgxNjN9.pd3_L511QMULeLOD8QMJKz8b34sbUt9XDamKM1lvICM`;

const mockCharacters = [
    {id : 1,
    charname : 'Test',
    race : 'test',
    classname : 'test',
    level : 1}
]

const mockCharacter = {"character":
    {"id":1,
    "creatorID":1,
    "charName":"Mock Character",
    "race":"human",
    "subrace":"",
    "className":"wizard",
    "background":"sage",
    "alignment":"Lawful Good",
    "level":1,
    "exp":0,
    "str":9,
    "strMod":-1,
    "dex":14,
    "dexMod":2,
    "con":15,
    "conMod":2,
    "int":16,
    "intMod":3,
    "wis":11,
    "wisMod":0,
    "cha":13,
    "chaMod":1,
    "profBonus":2,
    "savingProfs":["intelligence","wisdom"],
    "skillProfs":["arcana","history","insight","investigation"],
    "jackOfAllTrades":false,
    "passPerc":10,"inspiration":0,
    "speed":40,
    "initiative":2,
    "armorClass":12,
    "hpMax":8,
    "hpCurr":8,
    "hpTemp":0,
    "hitDice":6,
    "hitDiceMax":1,
    "hitDiceCurr":1,
    "deathSaveSuccess":0,
    "deathSaveFail":0,
    "altResources":[{"max":2,"curr":2,"name":"test resource"}],
    "personality":"Test personality",
    "ideals":"test ideals",
    "bonds":"test bonds",
    "flaws":"test flaws",
    "traits":[{"id":1,"charID":1,"name":"Test Trait","source":"Class","description":"this is a test trait"}],
    "features":[{"id":1,"charID":1,"name":"Test Feature","source":"Class","description":"this is a test feature"}],
    "languages":["test language"],
    "equipProfs":["test equip prof"],
    "equipment":[{"name":"test equipment","amount":1}],
    "copper":50,
    "silver":10,
    "gold":100,
    "attacks":[{"id":1,"charID":1,"name":"Atk 1","attackSkill":"wis","attackMod":1,"isProf":true,"dmgDice":8,"numDice":1,"dmgSkill":"wis","dmgMod":1,"dmgType":"Psychic","altDmgDice":0,"altNumDice":0,"altDmgSkill":"","altDmgMod":0,"altDmgType":"","description":"Custom attack 1 for Gale","savingSkill":"wis","savingEffect":"Half Damage","range":"Melee"}],
    "spellAbility":"int",
    "spellSaveDC":null,
    "spellAtkBonus":null,
    "cantripsKnown":3,
    "cantrips":[
    {"index":"fire-bolt",
    "name":"Fire Bolt",
    "description":"You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried. This spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).",
    "higherLevels":[],
    "range":"120 feet",
    "duration":"Instantaneous",
    "concentration":false,
    "ritual":false,
    "school":{"index":"evocation","name":"Evocation","url":"/api/magic-schools/evocation"},
    "castingTime":"1 action",
    "attackType":"ranged",
    "damage":{
        "damage_type":{"index":"fire","name":"Fire","url":"/api/damage-types/fire"},
        "damage_at_character_level":{"1":"1d10","5":"2d10","11":"3d10","17":"4d10"}},
    "areaOfAffect":null,
    "healLevels":null,
    "dc":null
    }],
    "levelOne":[
        {"index":"charm-person",
        "name":"Charm Person",
        "description":"You attempt to charm a humanoid you can see within range. It must make a wisdom saving throw, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance. When the spell ends, the creature knows it was charmed by you.",
        "higherLevels":["When you cast this spell using a spell slot of 2nd level or higher, you can target one additional creature for each slot level above 1st. The creatures must be within 30 feet of each other when you target them."],
        "range":"30 feet",
        "duration":"1 hour",
        "concentration":false,
        "ritual":false,
        "school":{"index":"enchantment","name":"Enchantment","url":"/api/magic-schools/enchantment"},
        "castingTime":"1 action",
        "attackType":null,
        "damage":null,
        "areaOfAffect":null,
        "healLevels":null,
        "dc":{
            "dc_type":{
                "index":"wis",
                "name":"WIS",
                "url":"/api/ability-scores/wis"},
                "dc_success":"none"}
            }],
    "levelOneSlots":2,
    "levelOneLeft":2,
    "levelTwo":[],
    "levelTwoSlots":0,
    "levelTwoLeft":0,
    "levelThree":[],
    "levelThreeSlots":0,
    "levelThreeLeft":0,
    "levelFour":[],
    "levelFourSlots":0,
    "levelFourLeft":0,
    "levelFive":[],
    "levelFiveSlots":0,
    "levelFiveLeft":0,
    "levelSix":[],
    "levelSixSlots":0,
    "levelSixLeft":0,
    "levelSeven":[],
    "levelSevenSlots":0,
    "levelSevenLeft":0,
    "levelEight":[],
    "levelEightSlots":0,
    "levelEightLeft":0,
    "levelNine":[],
    "levelNineSlots":0,
    "levelNineLeft":0,
    "age":38,
    "height":"5 ft. 6 in.",
    "weight":"medium",
    "backstory":"Whats a god to a world-class wizard? Gale was once a formidable archmage in Waterdeep, but pushed his relationship with the goddess Mystra too far. Not satisfied with being her lover, Gale tried to impress her further and meddled with powers beyond even his abilities, his attempt leaving him cursed with an orb of Netherese magic trapped inside his body. The cataclysmic power of the orb has turned Gale into a weapon capable of annihilating an entire city, should he fail to control himself. Wracked with shame for his hubris, Gale retreated to his tower, first out of self-pity, and then out of necessity. His research led him to a means of keeping the orbs power contained, but only temporarily. Now, with the threat of ceremorphosis looming large can Gale see off both of the grim fates lurking within him, or is he doomed at every turn?",
    "appearance":"Brown mullet and unshaven beard.",
    "allies":"Tara the tressym is far more than Gales pet; she has been his only advisor and friend since he was brought low by the orb. Tease him though she might, Tara will do everything she can to keep Gale safe. Just dont say shes a cat."}}


export {mockUser, mockToken, mockCharacters, mockCharacter};